jobs:

- template: azure-template.yml
  parameters:
    name: Linux
    os: linux
    pip_prefix: sudo

- template: azure-template.yml
  parameters:
    name: MacOSX
    os: macosx

- template: azure-template.yml
  parameters:
    name: Windows
    os: windows
