jobs:
- job: ${{ format(parameters.name) }}
  pool:
    ${{ if eq(parameters.os, 'macosx') }}:
      vmImage: macOS 10.13
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: Ubuntu 16.04
    ${{ if eq(parameters.os, 'windows') }}:
      vmImage: vs2017-win2016
  ${{ if eq(parameters.os, 'linux') }}:
    container: astrofrog/ubuntu-with-python-3:latest

  steps:

  - ${{ if ne(parameters.os, 'linux') }}:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: pip install git+https://github.com/pyinstaller/pyinstaller.git
      displayName: Installing pyinstaller

    - script: pip install PyQt5 PyQtWebEngine
      displayName: Installing app dependencies

  - ${{ if eq(parameters.os, 'linux') }}:

    - script: start-xvfb
      displayName: Start XVFB

  - script: pip install voila ipywidgets
    displayName: Installing voila and related dependencies

  - script: pip freeze
    displayName: List dependencies

  - script: pyinstaller voila_qt_full.spec
    displayName: Building application in onedir mode

  # - ${{ if eq(parameters.os, 'linux') }}:
  #
  #   - script: dist/voila_qt_full/voila_qt_full --nonblocking
  #     displayName: Testing application

  - ${{ if eq(parameters.os, 'macosx') }}:

    - script: python fix_osx.py dist/voila_qt_full.app
      displayName: Fix application

    - script: rm -r dist/voila_qt_full
      displayName: Remove unused directory

  #   - script: dist/voila_qt_full.app/Contents/MacOS/voila_qt_full --nonblocking
  #     displayName: Testing application
  #
  # - ${{ if eq(parameters.os, 'windows') }}:
  #
  #   - script: .\dist\voila_qt_full\voila_qt_full --nonblocking
  #     displayName: Testing application

  - ${{ if eq(parameters.os, 'macosx') }}:

    - script: hdiutil create -volname "Voila Demo" -srcfolder dist -ov -format UDZO voila_demo.dmg
      displayName: Make DMG

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: voila_qt_full-${{ parameters.os }}
        targetPath: voila_demo.dmg

  - ${{ if eq(parameters.os, 'linux') }}:

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: voila_qt_full-${{ parameters.os }}
        targetPath: dist/voila_qt_full

  - ${{ if eq(parameters.os, 'windows') }}:

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: voila_qt_full-${{ parameters.os }}
        targetPath: dist\voila_qt_full
