jobs:
- job: ${{ format(parameters.name) }}
  pool:
    ${{ if eq(parameters.os, 'macosx') }}:
      vmImage: macOS 10.13
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: Ubuntu 16.04
    ${{ if eq(parameters.os, 'windows') }}:
      vmImage: vs2017-win2016
  ${{ if eq(parameters.os, 'linux') }}:
    container: astrofrog/ubuntu-with-python-3:latest

  steps:

  - ${{ if ne(parameters.os, 'linux') }}:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

  - ${{ if eq(parameters.os, 'linux') }}:

    - script: export PATH=$HOME/.local/python/bin:$PATH
      displayName: Setting PATH

  - script: pip install git+https://github.com/pyinstaller/pyinstaller.git
    displayName: Installing pyinstaller

  - script: pip install PyQt5 PyQtWebEngine
    displayName: Installing app dependencies

  - script: pip freeze
    displayName: List dependencies

  - script: pyinstaller --onedir qtonly.py
    displayName: Building application in onedir mode

  - ${{ if eq(parameters.os, 'linux') }}:

    - script: dist/qtonly/qtonly
      displayName: Testing application

  - ${{ if eq(parameters.os, 'macosx') }}:

    - script: dist/qtonly/qtonly
      displayName: Testing application

  - ${{ if eq(parameters.os, 'windows') }}:

    - script: .\dist\qtonly\qtonly
      displayName: Testing application

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: dist
      includeRootFolder: false
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/qtonly-${{ parameters.os }}.tar.gz'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: qtonly-${{ parameters.os }}
      targetPath: $(Build.ArtifactStagingDirectory)
